# Generated by Django 5.0.1 on 2024-01-31 01:02

import django.core.files.storage
import propylon_document_manager.file_versions.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "url",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[propylon_document_manager.file_versions.validators.file_url],
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.IntegerField()),
                (
                    "content",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/workspaces/document-manager-assessment/src/propylon_document_manager/media"
                        ),
                        upload_to="",
                    ),
                ),
                ("hash", models.CharField(max_length=255, unique=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
