# Generated by Django 5.0.1 on 2025-05-25 10:15

import django.db.models.deletion
import propylon_document_manager.file_versions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_versions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', propylon_document_manager.file_versions.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='fileversion',
            name='custom_path',
            field=models.CharField(blank=True, help_text='Custom relative path (e.g., reports/2024/myfile.pdf). Will store at MEDIA_ROOT/<custom_path>', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=propylon_document_manager.file_versions.models.user_file_path),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='file_versions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
