# Generated by Django 5.0.1 on 2024-03-01 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="collaborators",
            field=models.ManyToManyField(blank=True, related_name="collaborators", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_versions",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
