# Generated by Django 5.0.1 on 2024-01-31 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("file_versions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="owned_files", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="write_users",
            field=models.ManyToManyField(related_name="write_files", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="file_versions.file"
            ),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="read_users",
            field=models.ManyToManyField(related_name="read_file_versions", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
