# Generated by Django 6.0.6 on 2026-06-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_versions", "0002_fileversion_storage_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fileversion",
            options={"ordering": ["-uploaded_at", "-version_number"]},
        ),
    ]
