# Generated by Django 5.0.1 on 2024-03-01 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_fileversion_collaborators_fileversion_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="file_versions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
