# Generated by Django 5.0.1 on 2025-05-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_alter_user_managers_fileversion_custom_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="version_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
