# Generated by Django 5.0.1 on 2024-03-01 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0003_alter_fileversion_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileversion",
            old_name="owner",
            new_name="owner_id",
        ),
    ]
