# Generated by Django 5.0.1 on 2024-03-01 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0004_rename_owner_fileversion_owner_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileversion",
            name="owner_id",
        ),
        migrations.AddField(
            model_name="fileversion",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
