# Generated by Django 5.0.1 on 2024-03-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0006_fileversion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="url",
            field=models.URLField(default="/test", max_length=512),
            preserve_default=False,
        ),
    ]
