# Generated by Django 5.0.1 on 2024-03-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0007_fileversion_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="url",
            field=models.CharField(max_length=512),
        ),
    ]
