# Generated by Django 5.0.1 on 2024-03-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0008_alter_fileversion_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="file_field",
            field=models.FileField(default="dwa", upload_to="uploads/%Y/%m/%d/"),
            preserve_default=False,
        ),
    ]
