# Generated by Django 5.0.1 on 2024-03-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0009_fileversion_file_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="version_number",
            field=models.IntegerField(default=1),
        ),
    ]
